DELETE http://localhost:3000/posts/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGVzIjpbImF1dGhvcml6ZWQgdXNlciJdLCJpYXQiOjE1Nzk2Mjc4NjcsImV4cCI6MTU3OTYyODQ2N30.ybTjyFdCmECwaI_W1hhi0KYT7Z3e4oQ9Wk__9dInszc

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "login": "trann2",
  "password": "trann2"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
  "refreshToken": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlhdCI6MTU3OTYwNDMxMn0.wgx5mBCvmXEW0sqXz3OxE6XhP4cXCCyXeGWy5-ACzEg"
}

###

POST http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInJvbGVzIjpbImF1dGhvcml6ZWQgdXNlciJdLCJpYXQiOjE1Nzk2Mjc4NjcsImV4cCI6MTU3OTYyODQ2N30.ybTjyFdCmECwaI_W1hhi0KYT7Z3e4oQ9Wk__9dInszc
Content-Type: application/json

{
	"description": "trannPostV3",
	"tags": [
		"trann",
		"hello",
    "123123123"
	]
}

###

POST http://localhost:3000/registration
Content-Type: application/json

{
  "login": "trann2",
  "password": "trann2",
  "confirmedPassword": "trann2",
  "firstName": "ann2",
  "lastName": "trepachko2"
}

###

GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE1Nzk2MjQxODMsImV4cCI6MTU3OTYyNDc4M30.vX5AnHc-lJ9vrxvCU7PckbfpB8BkevksZ5-EhGKn-fk