GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVzIjpbImF1dGhvcml6ZWQgdXNlciIsImFkbWluIl0sImlhdCI6MTU4MDQyMDI4MCwiZXhwIjoxNTgwNDIwODgwfQ.UYNN94fPfeLA2C9tBU8MKkNzUSH5E9ObWWEGggMXDrs

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "login": "trann",
  "password": "trann"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
  "refreshToken": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzAsImlhdCI6MTU3OTYwNDMxMn0.wgx5mBCvmXEW0sqXz3OxE6XhP4cXCCyXeGWy5-ACzEg"
}

###

POST http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVzIjpbImF1dGhvcml6ZWQgdXNlciIsImFkbWluIl0sImlhdCI6MTU4MDM5ODg0NSwiZXhwIjoxNTgwMzk5NDQ1fQ.TCZf94so5OFs2vItEYwxtehLBVtAOxhgHB6yzN_D7o4
Content-Type: application/json

{
	"description": "test2",
	"tags": [
		"test",
		"hello",
    "123123123"
	]
}

###

PUT http://localhost:3000/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVzIjpbImF1dGhvcml6ZWQgdXNlciIsImFkbWluIl0sImlhdCI6MTU4MDQyMDI4MCwiZXhwIjoxNTgwNDIwODgwfQ.UYNN94fPfeLA2C9tBU8MKkNzUSH5E9ObWWEGggMXDrs
Content-Type: application/json

{
  "description": "UPDATED UPDATED UPDATED UPDATED UPDATED"
}

###

POST http://localhost:3000/registration
Content-Type: application/json

{
  "login": "trann2",
  "password": "trann2",
  "confirmedPassword": "trann2",
  "firstName": "trann2",
  "lastName": "trann2"
}

###

GET http://localhost:3000/posts?page=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVzIjpbImF1dGhvcml6ZWQgdXNlciIsImFkbWluIl0sImlhdCI6MTU4MDM5ODg0NSwiZXhwIjoxNTgwMzk5NDQ1fQ.TCZf94so5OFs2vItEYwxtehLBVtAOxhgHB6yzN_D7o4

###

DELETE http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVzIjpbImF1dGhvcml6ZWQgdXNlciJdLCJpYXQiOjE1Nzk2MzYyNTMsImV4cCI6MTU3OTYzNjg1M30.I6n5lElS0q2xH0ZFDt3e7SVlWnYB9jWGTuLO0lanNoM

###

PUT http://localhost:3000/admin/users/5/give
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVzIjpbImF1dGhvcml6ZWQgdXNlciIsImFkbWluIl0sImlhdCI6MTU3OTYzNDUzOCwiZXhwIjoxNTc5NjM1MTM4fQ.mfKSt7QGw1MEfQmeFpkTmmkHR0nSgwvUc_Yf_bp7ns4
Content-Type: application/json

{
  "roleName": "admin"
}

###

PUT http://localhost:3000/admin/users/1/pickup
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGVzIjpbImF1dGhvcml6ZWQgdXNlciIsImFkbWluIl0sImlhdCI6MTU3OTYzNDgyMCwiZXhwIjoxNTc5NjM1NDIwfQ.1p-648h8kO_5tzkrOguzh1ZNSN4rvmJNGkvUyhavUBw
Content-Type: application/json

{
  "roleName": "admin"
}

###

DELETE http://localhost:3000/admin/delete-requests/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGVzIjpbImF1dGhvcml6ZWQgdXNlciIsImFkbWluIl0sImlhdCI6MTU3OTYzNTQxOCwiZXhwIjoxNTc5NjM2MDE4fQ.H6Ha9y1gPh3KHY4UGxDSfzX_ZrBCMLxIISJbu78K6q8
